/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klijent.forme;

import domen.AgentOsiguranja;
import domen.OpstiDomenskiObjekat;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import klijent.kontroler.KontrolerPrijavaNaSistem;

/**
 *
 * @author Korisnik
 */
public class PrijavaNaSistemFrm extends OpstaEkranskaForma {

    private final KontrolerPrijavaNaSistem kon;
    public PrijavaNaSistemFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); this.setLocationRelativeTo(null);
        kon = new KontrolerPrijavaNaSistem(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKorisnicko = new javax.swing.JLabel();
        txtKorisnicko = new javax.swing.JTextField();
        lblLozinka = new javax.swing.JLabel();
        btnPrijaviSe = new javax.swing.JButton();
        txtSifra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Uloguj se");

        lblKorisnicko.setText("Korisničko ime:");

        lblLozinka.setText("Lozinka:");

        btnPrijaviSe.setText("Prijavi se");
        btnPrijaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijaviSeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrijaviSe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKorisnicko)
                            .addComponent(lblLozinka))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKorisnicko)
                            .addComponent(txtSifra, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKorisnicko)
                    .addComponent(txtKorisnicko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLozinka)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrijaviSe)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrijaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijaviSeActionPerformed
        // TODO add your handling code here:
        kon.prijaviSe();
    }//GEN-LAST:event_btnPrijaviSeActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijaviSe;
    private javax.swing.JLabel lblKorisnicko;
    private javax.swing.JLabel lblLozinka;
    private javax.swing.JTextField txtKorisnicko;
    private javax.swing.JPasswordField txtSifra;
    // End of variables declaration//GEN-END:variables

    @Override
    public OpstiDomenskiObjekat kreirajObjekat() {
        return (OpstiDomenskiObjekat) new AgentOsiguranja();
    }

    public void setTxtKorisnicko(JTextField txtKorisnicko) {
        this.txtKorisnicko = txtKorisnicko;
    }

    public void setTxtSifra(JTextField txtSifra) {
        this.txtSifra = (JPasswordField) txtSifra;
    }

    public JTextField getTxtKorisnicko() {
        return txtKorisnicko;
    }

    public JTextField getTxtSifra() {
        return txtSifra;
    }
    
    
}
